export const metadata = {
  title: 'Terms of Service | Teveles',
}

export default function TermsPage() {
  return (
    <div className="py-16 md:py-24">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-4xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-10">Last updated: March 2026</p>

        <div className="space-y-10">

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">1. Acceptance of Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              By accessing or using the Teveles platform (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. These terms apply to all users, including beta participants and future subscribers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">2. Use of Service</h2>
            <p className="text-gray-600 leading-relaxed mb-3">
              Teveles is a fitness analytics and AI coaching platform designed for personal, non-commercial use by individual athletes. You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-600">
              <li>Use the Service for any illegal purpose or in violation of any applicable law</li>
              <li>Attempt to access another user&apos;s account or data</li>
              <li>Use automated tools to scrape, crawl, or extract data from the Service</li>
              <li>Reverse engineer or attempt to extract source code from the platform</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
              <li>Use the Service to provide competing services</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">3. Account Responsibilities</h2>
            <p className="text-gray-600 leading-relaxed">
              You are responsible for maintaining the confidentiality of your account credentials. You are responsible for all activity that occurs under your account. You must notify us immediately at{' '}
              <a href="mailto:hello@teveles.com" className="text-blue-600 hover:underline">hello@teveles.com</a>{' '}
              if you suspect unauthorized access to your account. Teveles reserves the right to suspend or terminate accounts that violate these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">4. Garmin Integration</h2>
            <p className="text-gray-600 leading-relaxed">
              The Service integrates with Garmin&apos;s Health API to access your activity and health data. By connecting your Garmin account, you authorize Teveles to access data available through this API on your behalf. Your use of Garmin&apos;s services is also subject to Garmin&apos;s own Terms of Service and Privacy Policy. Teveles is not affiliated with or endorsed by Garmin.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">5. Intellectual Property</h2>
            <p className="text-gray-600 leading-relaxed">
              The Teveles platform, including its software, design, algorithms, and content, is owned by Teveles and protected by intellectual property laws. You retain ownership of the raw data you bring to the platform (your Garmin data). Teveles retains ownership of the derived analytics, charts, models, and insights generated by the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">6. Disclaimer</h2>
            <p className="text-gray-600 leading-relaxed">
              THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. Teveles does not warrant that the Service will be uninterrupted, error-free, or accurate at all times. The analytics and AI insights provided are for informational purposes only and do not constitute medical advice. Always consult a qualified healthcare professional before making decisions about your health or training based on data from the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">7. Limitation of Liability</h2>
            <p className="text-gray-600 leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, TEVELES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE. Our total liability to you for any claim arising from these Terms or the Service shall not exceed the amount you paid for the Service in the 12 months preceding the claim, or $50, whichever is greater.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">8. Changes to Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              We may update these Terms from time to time. We will notify you of significant changes via email or an in-app notice. Continued use of the Service after changes are posted constitutes your acceptance of the updated Terms. We encourage you to review these Terms periodically.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">9. Contact</h2>
            <p className="text-gray-600 leading-relaxed">
              For questions about these Terms, please contact us at:{' '}
              <a href="mailto:hello@teveles.com" className="text-blue-600 hover:underline">hello@teveles.com</a>
            </p>
          </section>

        </div>
      </div>
    </div>
  )
}
